# Generated by Django 3.2.3 on 2021-07-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Side',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('taste', models.CharField(choices=[('SW', 'Sweet'), ('SO', 'Sour'), ('SA', 'Salty'), ('BI', 'Bitter')], default='SW', max_length=2, verbose_name='taste')),
            ],
        ),
    ]
